### ISSUE TITLE
Light colored profiles do not recolor text properly

### ISSUE THREAD

**Issue by madibye** [catppuccin/discord#54]
demonstration of what i mean (macchiatto on the left, no theme on the right)

![image](https://user-images.githubusercontent.com/10574583/199036237-f5ce0a4f-19bf-4e6d-bc16-dd3872f7fe3f.png) ![image](https://user-images.githubusercontent.com/10574583/199035796-01916234-38ac-4056-9ed4-309aefe04f14.png)

dark colored profiles appear just fine on this theme (light text on dark bg). frappe and mocha also have this issue, while latte works fine.

**Comment by ToxicAven** [comment]
This is because discord uses the `theme-light` class for these user popouts, which is likely interfering with the `theme-dark` styling of frappe, mocha and macchiato, by checking for `[class*="profileColors-"]` and not applying the text changes should fix the problem.

**Comment by nekowinston** [comment]
In Discord's Settings > Accessibility > Profile Colors, you can turn on this setting to force user profiles to sync with your theme.

Don't really understand why that's not the default setting. I should probably document this.

![image](https://user-images.githubusercontent.com/79978224/199803563-e6e6bad2-3351-4c1c-8e6f-15875042f848.png)

**Comment by madibye** [comment]
This issue was partially fixed a while ago, but still affects various UI elements on light-colored user profiles. On the base profile screen when clicking on a user's popout, the "Message @user" text still is too light, as well as the discord symbol next to the join date and the note add text arguably (could be worse on some other shades)
![image](https://user-images.githubusercontent.com/10574583/216808779-696248cb-aa6b-45b3-a538-e6c7d9e92576.png) 

Problems are significantly worse on the full user profile page. The user text and panel text are too bright, as well as the dots for the dropdown menu and the note text again
![Discord_7amxnyFA2T](https://user-images.githubusercontent.com/10574583/216808886-d4963cde-cd95-4316-98de-ba05db18cd0e.png)

Also affects the full page on mutual servers and mutual friends (I am too skittish to show my mutual friends but anyway)
![Discord_5L1YDNkB31](https://user-images.githubusercontent.com/10574583/216808897-b41f849c-48a6-48d8-a26b-eaf2600df1e3.png)

**Comment by rubyowo** [comment]
It's been partially fixed in #127
textarea placeholders still aren't the right color however since i can't find how it's set.

**Comment by rubyowo** [comment]
It's been partially fixed in #127
textarea placeholders still aren't the right color. However, since i can't find how it's set.
